# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/1342b145-0f63-4abf-974e-1d8d6803754e";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2CA4-DF39";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  fileSystems."/mnt/data" = {
    device = "/dev/disk/by-uuid/988C9B208C9AF7C8";
    fsType = "ntfs";
    options = [ "nofail" "uid=1000" "gid=100" ];
  };

  fileSystems."/mnt/primary" = {
    device = "/dev/disk/by-uuid/5C0A5CA80A5C8146";
    fsType = "ntfs";
    options = [ "nofail" "uid=1000" "gid=100" ];
  };

  fileSystems."/mnt/programming" = {
    device = "/dev/disk/by-uuid/8fa60935-54db-4341-8894-fb6d8a1b2dc6";
    fsType = "ext4";
    options = [ "nofail" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
